// src/components/Alert.svelte
<script module lang="ts">
    import type { Snippet } from "svelte";
    export interface Props {
        children: Snippet;
    }
</script>

<script lang="ts">
    let { children }: Props = $props();
</script>

<div class="alert">
    <div class="icons">
        <svg viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path
                fill-rule="evenodd"
                d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z"
                clip-rule="evenodd"
            ></path>
        </svg>
    </div>
    <h3>{@render children()}</h3>
</div>

// src/components/Alert.tsx
import type { PropsWithChildren } from "react";

export function Alert({ children }: PropsWithChildren) {
    return (
        <div className="alert">
            <div className="icons">
                <svg viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path
                        fill-rule="evenodd"
                        d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z"
                        clip-rule="evenodd"
                    ></path>
                </svg>
            </div>
            <h3>{children}</h3>
        </div>
    );
}
