// src/components/LikeButton.tsx
import { actions } from 'astro:actions';
import { useAction } from '../lib/action';
import { useRef, useState } from 'react';

export namespace LikeButton {
    export interface Props {
        postId: number;
        likeCount: number;
        isLiked: boolean;
    }
}

export function LikeButton(props: LikeButton.Props) {
    const [likes, like] = useAction(actions.like);
    const [isLiked, setIsLiked] = useState(props.isLiked);

    const initialResult = useRef(props.likeCount);
    const result = likes.result ? likes.result : initialResult.current;
    initialResult.current = result;

    // Optimistic UI
    const likeCount = likes.pending
        ? // By this time we've set isLiked to its optimistic value
          isLiked
            ? result + 1
            : result - 1
        : result;

    const clickLikeButton = async () => {
        setIsLiked((isLiked) => !isLiked);
        await like({ postId: props.postId });
        if (likes.error) {
            setIsLiked((isLiked) => !isLiked);
        }
    };

    return (
        <>
            <span className="text-sm">{likeCount}</span>
            <button className="btn-heart" disabled={likes.pending} onClick={clickLikeButton}>
                {isLiked ? '♥︎' : '♡'}
            </button>
        </>
    );
}

// src/components/LikeButton.svelte
<script module lang="ts">
    export interface Props {
        postId: number;
        likeCount: number;
        isLiked: boolean;
    }
</script>

<script lang="ts">
    import { Action } from "../lib/actions.svelte";
    import { actions } from "astro:actions";
    import { deriveFrom } from "../lib/derive-from.svelte";

    let props: Props = $props();

    const likes = new Action(actions.like);
    let isLiked = $state(props.isLiked);

    const result = deriveFrom<number>(props.likeCount, previous =>
        likes.result ? likes.result : previous,
    );

    // Optimistic UI
    const likeCount = $derived.by(() => {
        if (likes.pending) {
            // By this time we've set isLiked to its optimistic value
            return isLiked ? result() + 1 : result() - 1;
        }
        return result();
    });

    async function clickLikeButton() {
        isLiked = !isLiked;
        await likes.submit({ postId: props.postId });

        if (likes.error) {
            isLiked = !isLiked;
        }
    }
</script>

<span class="text-sm">{likeCount}</span>
<button class="btn-heart" disabled={likes.pending} onclick={clickLikeButton}>
    {#if isLiked}
        ♥︎
    {:else}
        ♡
    {/if}
</button>
